### ISSUE TITLE
Move example code from Gdrive to GitHub

### ISSUE THREAD

**Issue by svonava** [superlinked/VectorHub#115]
The [KG article](https://hub.superlinked.com/answering-questions-with-knowledge-graph-embeddings) has a code link pointing to GDrive - it's difficult to view and there is no way for others to submit a fix if there is a bug there and we might lose access in the future.

Let's please move it to this GitHub repo!

<img width="764" alt="image" src="https://github.com/superlinked/VectorHub/assets/1493333/6dbf7b83-d70d-43de-9649-c561f95dbca4">

**Comment by svonava** [comment]
cc @ricsi98

**Comment by AruneshSingh** [comment]
Added [here](https://github.com/superlinked/VectorHub/blob/main/docs/assets/use_cases/knowledge_graph_embedding/kge_demo.ipynb), and updated link.
