### ISSUE TITLE
Typo on loom descriptiom

### ISSUE THREAD

**Issue by arijitroy003** [superlinked/VectorHub#15]
![image](https://github.com/superlinked/VectorHub/assets/43462564/47f43017-b075-45d7-bd7a-da69b06ee9d1)

First line on description - Vectelhub ->VectorHub

**Comment by ClaireSuperlinked** [comment]
@AruneshSingh - please see above, can you make the edit in Loom?

**Comment by ClaireSuperlinked** [comment]
We are recording a new loom tutorial with the updated process. Will resolve once this is complete

**Comment by ClaireSuperlinked** [comment]
new video created so resolving
