### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by andreidvornic** [superlinked/VectorHub#16]
https://hub.superlinked.com/data-sources - I'd make the images bigger, hard to read without click through (same all on pages actually). Also some of the images (e.g. the meme at the top  here https://hub.superlinked.com/vector-compute take a very long time to load - maybe try to compress?)

https://hub.superlinked.com/vector-compute - this is too big when you click through, you have to fight with it to see properly (using Chrome), likely will give up. Same for https://hub.superlinked.com/vector-compute - needs a review on all pages I think.

https://hub.superlinked.com/contributing Use cases => Blog; Tools => Toolbox

**Comment by ClaireSuperlinked** [comment]
Thanks for submitting this feedback. We will look into this now and update you when the edits are made

**Comment by ClaireSuperlinked** [comment]
Updated contribution section. Working on solutions to the images problem :)

**Comment by ClaireSuperlinked** [comment]
Image now resolved so closing issue
