### ISSUE TITLE
Let's be careful with new acronyms

### ISSUE THREAD

**Issue by svonava** [superlinked/VectorHub#18]
I understand that we are trying to coing vector compute as VC, but I'd spell it out at least in the landing page of the article

Basically all the instances where VC is mentioned alone I think could be confusing:
![image](https://github.com/superlinked/VectorHub/assets/1493333/8ecf10d4-48ca-41fc-9857-575fdbc52303)

Reference:
https://hub.superlinked.com/vector-compute

**Comment by ClaireSuperlinked** [comment]
Updated images with full title so resolving
