### ISSUE TITLE
Horizontal scrolling hides data

### ISSUE THREAD

**Issue by Kerollmops** [superlinked/VectorHub#212]
I was lucky to have a friend who told me that there are more columns on the right of this table. I spent approximately 20 minutes on it and have yet to notice. You can only scroll when the mouse is over the data rows and not the header rows.

**Comment by AruneshSingh** [comment]
Thanks a lot @Kerollmops! We're working on a fix. 

On a related note, what would be an ideal way for you to navigate so many attributes?

**Comment by Kerollmops** [comment]
Thank you!

> On a related note, what would be an ideal way for you to navigate so many attributes?

Maybe a big arrow on the right on a blurry white background you can click on to scroll to the right.

**Comment by ClaireSuperlinked** [comment]
Thanks for your feedback on this - we have added this to the roadmap and will let you know once we have something for you to look at.

**Comment by ClaireSuperlinked** [comment]
@AruneshSingh - can we get an update on the nav updates that we're pushing next week?

**Comment by ClaireSuperlinked** [comment]
@Kerollmops we have published updates to make the Nav cleaner and created a new onboarding process to show how to navigate & get the most from the table. Your feedback here was really helpful. Thanks and hope you like the new version: https://superlinked.com/vector-db-comparison
