### ISSUE TITLE
add embeddings comparison  it is clear embeddings  are bad

### ISSUE THREAD

**Issue by Sandy4321** [superlinked/VectorHub#262]
add embeddings comparison 
The pervasive silence in the scientific community regarding the pitfalls of embeddings starkly contrasts with their widespread use, raising questions about why many researchers gloss over this easily understood issue, possibly to preserve the status quo or avoid confronting the limitations of current methodologies

Many scientists remain silent on the flaws of embeddings, a concerning trend that underscores a reluctance to challenge established norms and methodologies

Many experts don't talk about how bad embeddings can be, which shows they're often avoiding hard truths

but it is clear embeddings  are bad 
video 
https://www.youtube.com/watch?v=YZTThlPg0rU&t=220s
code 
https://github.com/tanchongmin/strictjson/blob/main/Experiments/Context-Dependent-Embeddings.ipynb

**Comment by ClaireSuperlinked** [comment]
Hello,Vectors are the medium into which ML models encoded information for decades and they do so successfully - so we know that this works. However, the tooling around the design, training and inference of embedding models is still very early and we share your frustration with the space. 

Thank you for raising this issue however it is currently out of scope for the VDB comparison table. We will look into different tools and resources as we continue to build out vectorhub so will bear this in mind for something we can cover.
