### ISSUE TITLE
feat(comparison): Add pgvecto.rs

### ISSUE THREAD

**Issue by gaocegege** [superlinked/VectorHub#352]
If you believe that pgvecto.rs should be included, I am eager to assist with its addition to the list.

https://github.com/tensorchord/pgvecto.rs is the vector search extension in Postgres.

**Comment by AruneshSingh** [comment]
@superlinked/vdb-table-maintainers Please have a look at this and evaluate

**Comment by dhruv-anand-aintech** [comment]
Hi @gaocegege, yes, of course. It would be great to have pgvecto.rs on the list. You can send a PR that adds a new file under `docs/tools/vdb_table/data` with the appropriate references for each feature supported in this repo. Eg: https://github.com/superlinked/VectorHub/pull/120/files

We will review the PR and have it merged.
