### ISSUE TITLE
Update info request for Milvus

### ISSUE THREAD

**Issue by yiwen92** [superlinked/VectorHub#355]
- [ ] Typo
- [X ] Content out of date

**Please share the typo or the content which is out of date. (The section, content excerpt or screenshot would be appreciated)**
<img width="853" alt="image" src="https://github.com/superlinked/VectorHub/assets/34636520/bb266da4-4cfa-4293-9636-5a8172999999">
<img width="876" alt="image" src="https://github.com/superlinked/VectorHub/assets/34636520/3472ae6c-89ea-4c80-8097-cbbb26d2e6c4">

**Please share your source in case the content is out of date**
1. Zilliz Cloud is the managed milvus - https://zilliz.com/pricing

2. Milvus support text model in https://milvus.io/docs/embeddings.md, you can call emb libs to use different models.

**Comment by svonava** [comment]
Thanks @yiwen92 - FYI, the table is backed by data stored here:
https://github.com/superlinked/VectorHub/blob/main/docs/tools/vdb_table/data/milvus.json

Could you submit a PR? Don't forget to link the appropriate documentation for each feature.

**Comment by yiwen92** [comment]
Done

**Comment by AruneshSingh** [comment]
@yiwen92 Is this resolved? I don't see a PR open for this.

**Comment by svonava** [comment]
@AruneshSingh see https://github.com/superlinked/VectorHub/pull/354

**Comment by yiwen92** [comment]
> @yiwen92 Is this resolved? I don't see a PR open for this.

@AruneshSingh Now you can see the PR

**Comment by svonava** [comment]
I think this was merged in now, thanks @yiwen92
