### ISSUE TITLE
in the article "Answering Questions with Knowledge Graph Embeddings"

### ISSUE THREAD

**Issue by younggggger** [superlinked/VectorHub#358]
when i run :
# Get node and relation IDs
france = nodes["France"]
rel = edges["/location/location/contains"]
burgundy = nodes["Burgundy"]
riodj = nodes["Rio de Janeiro"]
bnc = nodes["Bonnie and Clyde"]

# Define triplets
head_entities = torch.tensor([france, france, france], dtype=torch.long)
relationships = torch.tensor([rel, rel, rel], dtype=torch.long)
tail_entities = torch.tensor([burgundy, riodj, bnc], dtype=torch.long)

# Score triplets using the model
scores = model(head_entities, relationships, tail_entities)
print(scores.tolist())

error:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[9], line 2
      1 # Get node and relation IDs
----> 2 france = nodes["France"]
      3 rel = edges["/location/location/contains"]
      4 burgundy = nodes["Burgundy"]

NameError: name 'nodes' is not defined

**Comment by ricsi98** [comment]
Thanks @younggggger for reaching out. 
As @svonava  pointed out, the code snippet provided in the blog post serves primarily as an illustrative tool for enhancing comprehension. However, the process of resolving entity names for the [FB15k_237](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.datasets.FB15k_237.html#torch_geometric.datasets.FB15k_237) dataset can indeed be somewhat convoluted.

I've prepared a gist [here](https://gist.github.com/ricsi98/81138cd51e8fe7e15644805c2371bca0) that extracts ID-node index mappings. With these mappings, resolving entity names based on the IDs becomes feasible.

To illustrate, here's an [example](https://query.wikidata.org/#SELECT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP646%20%22%2Fm%2F0mm1q%22.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D%0A) of how you can resolve entity names using the Wikidata Query Service:
```
SELECT ?item ?itemLabel WHERE {
  ?item wdt:P646 "/m/0mm1q".
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
```

**Comment by ClaireSuperlinked** [comment]
@AruneshSingh is this updated in the article? If not let's get it changed as needed :)

**Comment by AruneshSingh** [comment]
Added the explanation and related examples in the article.
