### ISSUE TITLE
Improve styles for readability and aesthetics

### ISSUE THREAD

**Issue by prrao87** [superlinked/VectorHub#45]
- [ ] Typo
- [ ] Content out of date
- [x] Styles and appearance

Hi @AruneshSingh, happy new year. I was reading the blog and there are some areas where the readability and appearance could be improved via CSS/JS (hopefully Archbee allows customizing these).

1. Light mode colors for in-line code make it really hard to read
2. Math equations/expressions not being rendered

Sample post for reference: [Answering Questions with Knowledge Graph Embeddings](https://hub.superlinked.com/answering-questions-with-knowledge-graph-embeddings).

## Light mode colors for in-line code

When reading in light mode, the in-line code text color is the same as the background. In dark mode, this isn't an issue.

### Light mode:
![image](https://github.com/superlinked/VectorHub/assets/35005448/6aa856a3-26b1-4257-a39a-92646ef39c64)

### Dark mode
![image](https://github.com/superlinked/VectorHub/assets/35005448/71e5e8ea-74fd-46c6-ab2e-9338311acd33)

## Math rendering

I don't think Katex or MathJax (or whatever it is that Archbee supports for in-line math equations/expressions) has been enabled throughout the blog? As can be seen in [this section](https://hub.superlinked.com/answering-questions-with-knowledge-graph-embeddings#J8HPS), they aren't being rendered.

![image](https://github.com/superlinked/VectorHub/assets/35005448/0d49adef-a396-46ac-9d00-ae970a824743)

**Comment by ClaireSuperlinked** [comment]
Thanks @prrao87 for this. We have raised the lightmode rendering issue with the support team as it seems to switch between readable and unreadable colour ways even if you just stay in light mode. 

On the math - we will look into this

**Comment by ClaireSuperlinked** [comment]
Quick update here - on the math, we are moving all equations to images and in line math formatting isn't available.

On the lightmode rendering - this issue persists but we are looking at other options for hosting VectorHub over the next few weeks. Resolving the issue will be one of our acceptance criteria on moving

**Comment by prrao87** [comment]
Yeah, it should be a pretty simple css change in a conventional static site. I think there should be plenty of other options for hosting if they can't resolve this in a reasonable time.

**Comment by ClaireSuperlinked** [comment]
Update - currently researching alternatives. Please share any additional functionality you think could improve the overall asthethics and readability on this thread :)

**Comment by ClaireSuperlinked** [comment]
Closing this issue as we have now got a route forward to resolving these issues which will be developed in March! All possible fixes in the short term have been done. Looking forward to sharing the new UI shortly :)
